import React from 'react';
export const logisticsDetails = () => <div>logistics distinct</div>;
export const logistics_detail_0 = (p:any)=> <div>logistics 0 volunteer logistics</div>;
export const logistics_detail_1 = (p:any)=> <div>logistics 1 transport</div>;
export const logistics_detail_2 = (p:any)=> <div>logistics 2 routes</div>;
export const logistics_detail_3 = (p:any)=> <div>logistics 3 dispatch</div>;
export const logistics_detail_4 = (p:any)=> <div>logistics 4 volunteer logistics</div>;
export const logistics_detail_5 = (p:any)=> <div>logistics 5 transport</div>;
export const logistics_detail_6 = (p:any)=> <div>logistics 6 routes</div>;
export const logistics_detail_7 = (p:any)=> <div>logistics 7 dispatch</div>;
export const logistics_detail_8 = (p:any)=> <div>logistics 8 volunteer logistics</div>;
export const logistics_detail_9 = (p:any)=> <div>logistics 9 transport</div>;
export const logistics_detail_10 = (p:any)=> <div>logistics 10 routes</div>;
export const logistics_detail_11 = (p:any)=> <div>logistics 11 dispatch</div>;
export const logistics_detail_12 = (p:any)=> <div>logistics 12 volunteer logistics</div>;
export const logistics_detail_13 = (p:any)=> <div>logistics 13 transport</div>;
export const logistics_detail_14 = (p:any)=> <div>logistics 14 routes</div>;
export const logistics_detail_15 = (p:any)=> <div>logistics 15 dispatch</div>;
export const logistics_detail_16 = (p:any)=> <div>logistics 16 volunteer logistics</div>;
export const logistics_detail_17 = (p:any)=> <div>logistics 17 transport</div>;
export const logistics_detail_18 = (p:any)=> <div>logistics 18 routes</div>;
export const logistics_detail_19 = (p:any)=> <div>logistics 19 dispatch</div>;